apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covid19-stats-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        patchType: Prefix
        backend:
          service:
            name: covid19-stats-service
            port:
              number: 5000