--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: covid19-stats
  name: covid19-stats-service
spec: 
  ports: 
    - nodePort: 31000
      port: 80
      targetPort: 80
  selector: 
    app: covid19-stats
  type: NodePort
