---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: nginx-ns
  labels:
    app: app-service
    tier: backend
spec:
  selector:
    app: app-service
    tier: backend
  ports:
  - port: 5000
    protocol: TCP
