apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx-ns
data:
  nginx.conf: |
    worker_processes 1;

    user nobody nogroup;
    pid /tmp/nginx.pid;
    error_log /dev/stdout;

    events {
      worker_connections 1024; # increase if you have lots of clients
      accept_mutex off; # set to 'on' if nginx worker_processes > 1
    }

    http {
      include mime.types;
      default_type application/octet-stream;
      access_log /dev/stdout combined;
      sendfile off;

      upstream app_server {
        server unix:/tmp/gunicorn.sock fail_timeout=0;
      }

      server {

        listen 80;
        location  / {
          proxy_pass http://app-service.nginx-ns.svc.cluster.local:5000;
          proxy_redirect off;
          proxy_request_buffering off;

        }
      }
    }