---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
  labels:
    app: nginx
    tier: backend
spec:
  selector:
    app: nginx-service
    tier: backend
#  type: ClusterIP
  ports:
  - port: 80
#    targetPort: 5000
    protocol: TCP
#  externalIPs:
#    - 168.1.226.29
