---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx-deployment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts:
            - name: nginx-configmap-storage
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      #              mountPath: /etc/nginx
      volumes:
        - name: nginx-configmap-storage
          configMap:
            name: nginx-configmap # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: ../nginx.conf