---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
  labels:
    app: nginx
    tier: backend
spec:
  selector:
    app: nginx-service
    tier: backend
  type: ClusterIP
  ports:
  - port: 80
#    nodePort: 31000
#    targetPort: 5000
    protocol: TCP
  externalIPs:
    - 192.168.99.102
