---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
  labels:
    app: nginx
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
#  type: ClusterIP
#  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
#    nodePort: 31000
#    targetPort: 5000
#  externalIPs:
#    - 192.168.99.102
