apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    worker_processes 1;

    user nobody nogroup;
    pid /tmp/nginx.pid;
    error_log /tmp/nginx.error.log;

    events {
      worker_connections 1024; # increase if you have lots of clients
      accept_mutex off; # set to 'on' if nginx worker_processes > 1
    }

    http {
      include mime.types;
      default_type application/octet-stream;
      access_log /tmp/nginx.access.log combined;
      sendfile off;

      upstream app_server {
        server unix:/tmp/gunicorn.sock fail_timeout=0;
      }

     server {
        # if no Host match, close the connection to prevent host spoofing
        listen 5000 default_server;
        return 444;
      }

     server {
            listen 80 default_server;
            keepalive_timeout 5;

        location / {
          proxy_redirect off;
          proxy_pass http://app-service:5000;
          proxy_request_buffering off;
        }
      }
    }